# Generated by Django 4.2.5 on 2023-10-19 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default='descp default', help_text='Descripción del evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.usuario'),
        ),
    ]
