# Generated by Django 4.2.5 on 2023-10-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_nombre_evento_titulo_remove_usuario_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default='descp default', max_length=25),
        ),
    ]
